### ISSUE TITLE
Ready for Pen Test

### ISSUE THREAD

**Issue by cjhskippy** [CMSgov/cms-carts-seds#387]
- [ ] Establish User Accounts (#386 )
- [x] Architecture diagram provided to pen test lead (#422)
- [x] System in VAL environment
- [ ] URLs to Pen Test team
- [ ] "Production Ready" criteria met

- [ ] ~~Systems diagram~~

- [x] Business flow diagram (#421)

Pen Test is scheduled to begin the week of 9/28/2020.

**Comment by jgillis1** [comment]
@StephanieCoppel @TaraWilliamsPGH Should we close this one out with the Pen Test being complete?

**Comment by StephanieCoppel** [comment]
@jgillis1  yup!
