### ISSUE TITLE
User Authentication 

### ISSUE THREAD

**Issue by cjhskippy** [CMSgov/cms-carts-seds#392]
Collection of stories related to user authentication and activities permitted for each of the user roles.

Necessary for states to begin their 2020 CARTS report: 
- [x] Temporarily disable authentication ( #479 )
- [ ] User Roles in database ( #206 )
- [x] Connect React -> Django ( #481 )
- [x] Login page ( #300 )
- [ ] Re-enable authentication ( #480 )
