### ISSUE TITLE
File upload subtask: Create endpoint for metadata

### ISSUE THREAD

**Issue by cjhskippy** [CMSgov/cms-carts-seds#790]
The first step in a file upload if for the end user to signal that they want to upload a file.  The backend will take the user's request and what it knows about the user from their Okta authentication to decide if they have permission to upload the file.  This step is followed by #791

- [ ] Accepts metadata:
  - [ ] A name for the file to be uploaded.  Note that here, we mean the file name that will be shown to the user like "2020 Report", not the filename as stored in S3
  - [ ] The location in the form where users can find the upload.

- [ ] If the user has permission to upload a file, the API creates a record in the CARTS database indicating the existence of the file.
