### ISSUE TITLE
File upload subtask: Create S3 / Signed URL negotiation endpoint

### ISSUE THREAD

**Issue by cjhskippy** [CMSgov/cms-carts-seds#791]
This is the step after #790. After a user has provided the metadata needed for uploading a file, the CARTS backend needs to generate some information about the file and a signed URL that will allow the file to be stored in CARTS. Followed by #792

- [ ] Uses user's role and state association to determine if they have permission to upload a file
- If the user has permission:
   - [ ] generates a UUID for the file that includes the location in the form where the file will be found.
   - [ ] generates a signed URL
   - [ ] Returns UUID and signed URL to the client
- [ ] Rejects attempts to get a signed URL if the user does not have permission.
