### ISSUE TITLE
Minimum viable unit test

### ISSUE THREAD

**Issue by cannandev** [CMSgov/cms-carts-seds#91]
Create an initial set of unit tests to cover the most noticeable form errors (perhaps if an entire section or page doesn't appear?). An additional goal is to provide a structure that can be used when developing each new component in the future.

A/C:
- [ ] At least one unit test runs automatically on pull requests
- [ ] Failed tests prevent merge to master / deployment

Originally framed as "Write Enzyme unit tests for components", which is a fine direction if the team thinks that's the best way to get bang for our automated testing $$$.

**Comment by cannandev** [comment]
This ticket is an Epic for the actual application.

Examples:

- [ ] shallow tests to make sure header, footer, vertical nav elements render on the page
- [ ] Textfields echo whether the user text input was entered
- [ ] Component calculations are correct (percentage calculator, FPL range inputs)

**Comment by TaraWilliamsPGH** [comment]
@cannandev - can we close this or does it need to stay open?

**Comment by StephanieCoppel** [comment]
@GL2020-QM do we still need this? if so, please tag any related stories to this epic with this epic. if not, let me know and we can close. @cjhskippy  feel free to chime in here too!
